version: 0.1

phases:
    install:
         commands:
            - npm install 
            - npm install -g serverless
    post_build:
         commands:
            - serverless deploy --region us-east-1 -v